# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: alexandersabino.streamproxy
PackageVersion: 1.1.1
PackageLocale: pt-br
Publisher: Alexander Sabino
PackageName: StreamProxy
License: GPL-3.0
ShortDescription: a proxy for livestreams (streamlink or ffmpeg), see more in https://github.com/asabino2/streamproxy
ManifestType: defaultLocale
ManifestVersion: 1.1.0

